services:
  database:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      POSTGRES_HOST: "database"
      MODEL_PATH: "/models/yolov8n.onnx"
      CONFIG_PATH: "../alembic.ini"
      IS_DOCKER: "TRUE"
    command: ["python", "main.py"]
    env_file:
      - .env
    volumes:
      - ./models:/models
    ports:
      - "7000:7000"